name: sushi_room
description: SushiRoom App
publish_to: "none"

version: 1.1.2+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  animated_theme_switcher: ^2.0.8
  animations: ^2.0.8
  app_settings: ^5.0.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.3
  dynamic_color: ^1.6.6
  file_picker: ^8.0.3
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_database: ^11.0.0
  flutter:
    sdk: flutter
  flutter_fancy_tree_view: ^1.4.1
  flutter_i18n: ^0.35.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.2
  get: ^4.6.6
  google_fonts: ^6.0.0
  html: ^0.15.4
  http: ^1.1.0
  internet_connection_checker_plus: ^2.1.0
  location: ^6.0.2
  mobile_scanner: ^5.1.1
  ota_update: ^6.0.0
  package_info_plus: ^8.0.0
  permission_handler: ^11.0.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.1
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_pdfviewer: ^24.2.8
  universal_io: ^2.2.2
  url_launcher: ^6.1.14
  webview_flutter: ^4.4.1
  webview_universal: ^0.0.5

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/i18n/

  uses-material-design: true
