name: sushi_room
description: SushiRoom App
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_theme_switcher: ^2.0.8
  get: ^4.6.6
  shared_preferences: ^2.2.1
  device_info_plus: ^9.0.3
  dynamic_color: ^1.6.6
  google_fonts: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
