name: sushi_room
description: SushiRoom App
publish_to: "none"

version: 1.1.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  animated_theme_switcher: ^2.0.8
  animations: ^2.0.8
  app_settings: ^5.0.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.3
  dynamic_color: ^1.6.6
  file_picker: ^6.0.0
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_database: ^10.2.6
  flutter:
    sdk: flutter
  flutter_fancy_tree_view: ^1.4.1
  flutter_i18n: ^0.34.0
  flutter_keyboard_visibility: ^5.4.1
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.2
  get: ^4.6.6
  google_fonts: ^6.0.0
  location: ^5.0.3
  mobile_scanner: ^3.4.1
  permission_handler: ^11.0.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.1
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_pdfviewer: ^23.1.39
  universal_io: ^2.2.2
  url_launcher: ^6.1.14
  webview_flutter: ^4.4.1
  webview_universal: ^0.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/i18n/

  uses-material-design: true
